### ISSUE TITLE
What are $HOME, $DATA, $SSH_CONFIG, $GITINGNORE_GLOBAL?

### ISSUE THREAD

**Issue by tadao** [vochicong/datalab-nlp#5]
What are $HOME, $DATA, $SSH_CONFIG, $GITINGNORE_GLOBAL?

After build, I tried to compose up in your repository.
But I caught some errors.

> ERROR: for datalabnlp_datalab-nlp_1  Cannot create container for service datalab-nlp: create .: "." includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed
> ERROR: for datalab-nlp  Cannot create container for service datalab-nlp: create .: "." includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed
> ERROR: Encountered errors while bringing up the project.

Maybe your "docker-compose.yml" file is caused because I didn't set $HOME, $DATA, $SSH_CONFIG, $GITIGNORE_GLOBAL.
What should I set these env settings?

**Comment by vochicong** [comment]
I've added a sample file `.env.sample` for environment setting.
Copy it to `.env` and edit `.env` to your preference to define environment variables.

**Comment by tadao** [comment]
Thank you very much for your commits.
I've built your docker-compose, deploy my GCP and is running.
It succeeded!! thanks.

But I realized that MeCab is read only at "root" directory.
Is this usual?
When I create some directories, it's not read.

**Comment by vochicong** [comment]
You are welcome.
MeCab is installed by default settings.

**Comment by tadao** [comment]
Great.

I'm running this repository under GCloud.
`datalab create --image-name=gcr.io/${PROJECT_ID}/datalab-nlp datalab-nlp`
Of course, I push the latest version.

But it seems to override directories because my Cloud Datalab has only datalab dir but your repo samples dir.

**Comment by tadao** [comment]
Sorry,

my mount volume is older.
I delete all volumes and container, and recreate datalab project, and then I could run MeCab.

Thank you very much:)
