### ISSUE TITLE
Missing run.sh

### ISSUE THREAD

**Issue by bhueth** [vochicong/datalab-nlp#8]
run.sh is called in entrypoint.sh, but does not exist.

**Comment by vochicong** [comment]
Have you actually encountered any error?
run.sh is available from the [original googledatalab/datalab docker](https://github.com/googledatalab/datalab/blob/master/containers/datalab/run.sh).

**Comment by bhueth** [comment]
I can build and run successfully with run.sh in the googledatalab/datalab repository, but the app doesn't seem to function properly. The minitoolbar shows up (after a long wait), but not the link and file picker to launch a notebook.

**Comment by vochicong** [comment]
So, `run.sh` does exist, right?

**Comment by bhueth** [comment]
I moved run.sh from original GDL repo into your repo.

**Comment by vochicong** [comment]
Verified that `run.sh` is in `.gitignore`. I'm going to fix it.

**Comment by vochicong** [comment]
@bhueth I've fixed the issue in the latest commit above.
